### ISSUE TITLE
License: GPL or Apache 2

### ISSUE THREAD

**Issue by markusschaber** [gandulf/DsaTab#351]
I'm a bit confused about the license.

The readme states Apache 2.0, while the License.txt is GPL 3.

(I'm a DSA player, and one of my tasks in my day job as software engineer is to clear licensing issues of OSS software, that's why I'm a bit sensitive to such issues :-))

**Comment by gandulf** [comment]
Hello,
i'm guessing the correct one is Apache 2, since almost everything regarding
Android is licensed under it. But i habe to confess i haven't given it mich
thougt. Just copied what the others Werke using.
If you habe a professional advice i would be more than happy,
gandulf

Am 13.08.2016 12:32 schrieb "Markus Schaber" <notifications@github.com>:

**Comment by markusschaber** [comment]
IANAL, but simplified:
- For the code you wrote yourself, you can choose any license (or combination of them) you want.
- For the code you copied from somewhere else, you need to retain the original license and copyright notices. (This can be a bit hairy if you copied the code long time ago and cannot find the license and copyright info any more...)
- For code which was submitted / contributed to the project by others, one can assume that it uses the main license of the project, if there is no explicit license information. However, you usually cannot change the license of the project with their consent.

Apache 2 is a very nice and common license. If you want to choose the Apache 2 license, you can find text and html versions at the apache website: http://www.apache.org/licenses/
